services:

  postgres: 
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres_db
    volumes:
      - db-data:/var/lib/postgresql/data
      - .sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d postgres_db"]
      interval: 1m30s
      timeout: 5s
      retries: 3
      start_period: 5s

  mage:
    image: mageai/mageai
    container_name: mage_app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "6789:6789"
    volumes:
      - .:/home/src
    environment:
      - MAGE_DATABASE_CONNECTION_URL=postgresql://postgres_user:postgres_password@postgres:5432/postgres_db

  PgAdmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8085:80"

volumes:
  db-data: